# Final project

Импорты

In [68]:
import pandas as pd
import numpy as np
import math
from urllib import request
import requests
import warnings
from urllib.error import HTTPError, URLError
from tqdm import trange

In [69]:
df_ingridients = pd.read_excel('C:\\Google Drive\\School21\\Day15\\name_columns.xlsx')

In [70]:
df_ingr_filtr = df_ingridients['include'].isin(['д'])

In [71]:
df_filtr = df_ingridients.loc[df_ingridients['include'] == 'д']

# Пищевая ценность

Соберите в датафрейм всю информацию о пищевой ценности продуктов из подготовленного вами и отфильтрованного набора данных (только столбцы с продуктами). Используйте для этого следующий API.
Конвертируйте все значения в % от суточной нормы потребления. Сохраняйте только те ингридиенты, которые находятся в этой и этой таблицах.
Сохраните измененный датафрейм в CSV-файл, который вы будете использовать в своей основной программе.

In [72]:
def nutritional(food_product):
    url = f'https://api.nal.usda.gov/fdc/v1/foods/search?&api_key=GbdUmKfiXLcF2D9ob1U2eaP3OCbMpvoPK6IknB6s&query={food_product}'
    res = requests.get(url).json()
    Nutrients = {}
    try:
        x = res['foods'][0]['foodNutrients']
        for i in x:
            Nutrients[i['nutrientName']] = [i['value'], i['unitName']]
        return Nutrients
    except IndexError:
        Nutrients = 0
    return Nutrients

In [73]:
def table(Nutrients, food_product):
    cc = pd.DataFrame(list(pp.items()), columns = ['nutrition', 'value'])
    cc['measure'] = 0
    cc['food_product'] = food_product
    for i in range(len(cc)):
        x = cc.iloc[[i],[1]].value
        y = x[i]
        a = y[0]
        b = y[1]
        cc.iloc[[i],[1]] = a
        cc.iloc[[i],[2]] = b
        cc.iloc[[i],[3]] = food_product
    return cc

In [74]:
for i in trange(1, len(df_filtr)):
    x = df_filtr['name'].values[i]
    if i == 0:
        pp = nutritional(x)
        cc = table(pp, x)
        df_new = cc
    if i > 0:
        pp = nutritional(x)
        if pp != 0:
            cc = table(pp, x)
            df_new = pd.concat([df_new, cc])

100%|████████████████████████████████████████████████████████████████████████████████| 240/240 [12:49<00:00,  3.20s/it]

In [75]:
df_new.to_csv('C:\\Google Drive\\School21\\Day15\\Nutrition_url.csv')
df_new

                         nutrition value measure food_product
0                          Protein  16.7       G       rating
1                Total lipid (fat)  60.0       G       rating
2      Carbohydrate, by difference  20.0       G       rating
3                           Energy   633    KCAL       rating
4                    Sugars, Total  3.33       G       rating
..                             ...   ...     ...          ...
9                    Vitamin A, IU   530      IU       turkey
10  Vitamin C, total ascorbic acid   0.0      MG       turkey
11                     Cholesterol  34.0      MG       turkey
12        Fatty acids, total trans   0.0       G       turkey
13    Fatty acids, total saturated  0.42       G       turkey

[17230 rows x 4 columns]

In [76]:
nutr_url = pd.read_csv('C:\\Google Drive\\School21\\Day15\\Nutrition_url.csv')
nutr_url['nutrition'] = nutr_url['nutrition'].str.lower()

In [77]:
df_nutr_1 = pd.read_csv('C:\\Google Drive\\School21\\Day15\\Natur1.csv', header = 1)
df_nutr_1 = df_nutr_1.rename(columns = {'Food\rComponent': 'Nutrient', 'Adults and Children ≥ 4\ryears' : 'Adults and Children\r≥ 4 years'})
df_nutr_1

,Nutrient,Unit of measure,Adults and Children\r≥ 4 years,Infants through 12\rmonths,Children 1 through 3\ryears,Pregnant women and\rlactating women
0,Fat,Grams (g),178,30.0,239,178
1,Saturated fat,Grams (g),120,NaN,210,120
2,Cholesterol,Milligrams (mg),300,NaN,300,300
3,Total\rcarbohydrates,Grams (g),1275,95.0,2150,1275
4,Sodium,Milligrams (mg),"2,300",NaN,"1,500","2,300"
5,Dietary Fiber,Grams (g),128,NaN,214,128
6,Protein,Grams (g),150,NaN,213,NaN
7,Added sugars,Grams (g),150,NaN,225,150

In [78]:
df_nutr_2 = pd.read_csv('C:\\Google Drive\\School21\\Day15\\Natur2.csv', header = 1)
df_nutr_2 = df_nutr_2.drop([27, 28])
df_nutr_2

,Nutrient,Unit of measure,Adults and Children\r≥ 4 years,1Infants through 12\rmonths,Children 1 through 3\ryears,Pregnant women\rand lactating women
0,Vitamin A,Micrograms RAE2 (mcg),900,500,300,"1,300"
1,Vitamin C,Milligrams (mg),90,50,15,120
2,Calcium,Milligrams (mg),"1,300",260,700,"1,300"
3,Iron,Milligrams (mg),18,11,7,27
4,Vitamin D,Micrograms (mcg)3,20,10,15,15
5,Vitamin E,Milligrams (mg)4,15,5,6,19
6,Vitamin K,Micrograms (mcg),120,2.5,30,90
7,Thiamin,Milligrams (mg),1.2,0.3,0.5,1.4
8,Riboflavin,Milligrams (mg),1.3,0.4,0.5,1.6
9,Niacin,Milligrams NE5 (mg),16,4,6,18
10,Vitamin B6,Milligrams (mg),1.7,0.3,0.5,2
11,Folate6,Micrograms DFE7 (mcg),400,80,150,600
12,Vitamin B12,Micrograms (mcg),2.4,0.5,0.9,2.8
13,Biotin,Micrograms (mcg),30,6,8,35
14,Pantothenic acid,Milligrams (mg),5,1.8,2,7
15,Phosphorus,Milligrams (mg),"1,250",275,460,"1,250"
16,Iodine,Micrograms (mcg),150,130,90,290
17,Magnesium,Milligrams (mg),420,75,80,400
18,Zinc,Milligrams (mg),11,3,3,13
19,Selenium,Micrograms (mcg),55,20,20,70
20,Copper,Milligrams (mg),0.9,0.2,0.3,1.3
21,Manganese,Milligrams (mg),2.3,0.6,1.2,2.6
22,Chromium,Micrograms (mcg),35,5.5,11,45
23,Molybdenum,Micrograms (mcg),45,3,17,50
24,Chloride,Milligrams (mg),"2,300",570,"1,500","2,300"
25,Potassium,Milligrams (mg),"4,700",700,"3,000","5,100"
26,Choline,Milligrams (mg),550,150,200,550
29,Protein,Grams (g),NaN,11,NaN,871

In [79]:
df_nutr = pd.concat([df_nutr_1, df_nutr_2])
df_nutr

,Nutrient,Unit of measure,Adults and Children\r≥ 4 years,Infants through 12\rmonths,Children 1 through 3\ryears,Pregnant women and\rlactating women,1Infants through 12\rmonths,Pregnant women\rand lactating women
0,Fat,Grams (g),178,30.0,239,178,NaN,NaN
1,Saturated fat,Grams (g),120,NaN,210,120,NaN,NaN
2,Cholesterol,Milligrams (mg),300,NaN,300,300,NaN,NaN
3,Total\rcarbohydrates,Grams (g),1275,95.0,2150,1275,NaN,NaN
4,Sodium,Milligrams (mg),"2,300",NaN,"1,500","2,300",NaN,NaN
5,Dietary Fiber,Grams (g),128,NaN,214,128,NaN,NaN
6,Protein,Grams (g),150,NaN,213,NaN,NaN,NaN
7,Added sugars,Grams (g),150,NaN,225,150,NaN,NaN
0,Vitamin A,Micrograms RAE2 (mcg),900,NaN,300,NaN,500,"1,300"
1,Vitamin C,Milligrams (mg),90,NaN,15,NaN,50,120
2,Calcium,Milligrams (mg),"1,300",NaN,700,NaN,260,"1,300"
3,Iron,Milligrams (mg),18,NaN,7,NaN,11,27
4,Vitamin D,Micrograms (mcg)3,20,NaN,15,NaN,10,15
5,Vitamin E,Milligrams (mg)4,15,NaN,6,NaN,5,19
6,Vitamin K,Micrograms (mcg),120,NaN,30,NaN,2.5,90
7,Thiamin,Milligrams (mg),1.2,NaN,0.5,NaN,0.3,1.4
8,Riboflavin,Milligrams (mg),1.3,NaN,0.5,NaN,0.4,1.6
9,Niacin,Milligrams NE5 (mg),16,NaN,6,NaN,4,18
10,Vitamin B6,Milligrams (mg),1.7,NaN,0.5,NaN,0.3,2
11,Folate6,Micrograms DFE7 (mcg),400,NaN,150,NaN,80,600
12,Vitamin B12,Micrograms (mcg),2.4,NaN,0.9,NaN,0.5,2.8
13,Biotin,Micrograms (mcg),30,NaN,8,NaN,6,35
14,Pantothenic acid,Milligrams (mg),5,NaN,2,NaN,1.8,7
15,Phosphorus,Milligrams (mg),"1,250",NaN,460,NaN,275,"1,250"
16,Iodine,Micrograms (mcg),150,NaN,90,NaN,130,290
17,Magnesium,Milligrams (mg),420,NaN,80,NaN,75,400
18,Zinc,Milligrams (mg),11,NaN,3,NaN,3,13
19,Selenium,Micrograms (mcg),55,NaN,20,NaN,20,70
20,Copper,Milligrams (mg),0.9,NaN,0.3,NaN,0.2,1.3
21,Manganese,Milligrams (mg),2.3,NaN,1.2,NaN,0.6,2.6
22,Chromium,Micrograms (mcg),35,NaN,11,NaN,5.5,45
23,Molybdenum,Micrograms (mcg),45,NaN,17,NaN,3,50
24,Chloride,Milligrams (mg),"2,300",NaN,"1,500",NaN,570,"2,300"
25,Potassium,Milligrams (mg),"4,700",NaN,"3,000",NaN,700,"5,100"
26,Choline,Milligrams (mg),550,NaN,200,NaN,150,550
29,Protein,Grams (g),NaN,NaN,NaN,NaN,11,871

In [80]:
df_nutr = df_nutr.rename(columns = {'Adults and Children\r≥ 4 years': 'Norma'})
df_nutr = df_nutr[['Nutrient', 'Norma', 'Unit of measure']]
df_nutr['Nutrient'] = df_nutr['Nutrient'].str.lower()
df_nutr.Norma[29] = 50
df_nutr

                Nutrient  Norma        Unit of measure
0                    fat    178              Grams (g)
1          saturated fat    120              Grams (g)
2            cholesterol    300        Milligrams (mg)
3   total\rcarbohydrates   1275              Grams (g)
4                 sodium  2,300        Milligrams (mg)
5          dietary fiber    128              Grams (g)
6                protein    150              Grams (g)
7           added sugars    150              Grams (g)
0              vitamin a    900  Micrograms RAE2 (mcg)
1              vitamin c     90        Milligrams (mg)
2                calcium  1,300        Milligrams (mg)
3                   iron     18        Milligrams (mg)
4              vitamin d     20      Micrograms (mcg)3
5              vitamin e     15       Milligrams (mg)4
6              vitamin k    120       Micrograms (mcg)
7                thiamin    1.2        Milligrams (mg)
8             riboflavin    1.3        Milligrams (mg)
9                 niacin     16    Milligrams NE5 (mg)
10            vitamin b6    1.7        Milligrams (mg)
11               folate6    400  Micrograms DFE7 (mcg)
12           vitamin b12    2.4       Micrograms (mcg)
13                biotin     30       Micrograms (mcg)
14      pantothenic acid      5        Milligrams (mg)
15            phosphorus  1,250        Milligrams (mg)
16                iodine    150       Micrograms (mcg)
17             magnesium    420        Milligrams (mg)
18                  zinc     11        Milligrams (mg)
19              selenium     55       Micrograms (mcg)
20                copper    0.9        Milligrams (mg)
21             manganese    2.3        Milligrams (mg)
22              chromium     35       Micrograms (mcg)
23            molybdenum     45       Micrograms (mcg)
24              chloride  2,300        Milligrams (mg)
25             potassium  4,700        Milligrams (mg)
26               choline    550        Milligrams (mg)
29               protein     50              Grams (g)

In [81]:
df_nutr['Norma'].values[33] = 4.7

In [82]:
df_nutr

                Nutrient  Norma        Unit of measure
0                    fat    178              Grams (g)
1          saturated fat    120              Grams (g)
2            cholesterol    300        Milligrams (mg)
3   total\rcarbohydrates   1275              Grams (g)
4                 sodium  2,300        Milligrams (mg)
5          dietary fiber    128              Grams (g)
6                protein    150              Grams (g)
7           added sugars    150              Grams (g)
0              vitamin a    900  Micrograms RAE2 (mcg)
1              vitamin c     90        Milligrams (mg)
2                calcium  1,300        Milligrams (mg)
3                   iron     18        Milligrams (mg)
4              vitamin d     20      Micrograms (mcg)3
5              vitamin e     15       Milligrams (mg)4
6              vitamin k    120       Micrograms (mcg)
7                thiamin    1.2        Milligrams (mg)
8             riboflavin    1.3        Milligrams (mg)
9                 niacin     16    Milligrams NE5 (mg)
10            vitamin b6    1.7        Milligrams (mg)
11               folate6    400  Micrograms DFE7 (mcg)
12           vitamin b12    2.4       Micrograms (mcg)
13                biotin     30       Micrograms (mcg)
14      pantothenic acid      5        Milligrams (mg)
15            phosphorus  1,250        Milligrams (mg)
16                iodine    150       Micrograms (mcg)
17             magnesium    420        Milligrams (mg)
18                  zinc     11        Milligrams (mg)
19              selenium     55       Micrograms (mcg)
20                copper    0.9        Milligrams (mg)
21             manganese    2.3        Milligrams (mg)
22              chromium     35       Micrograms (mcg)
23            molybdenum     45       Micrograms (mcg)
24              chloride  2,300        Milligrams (mg)
25             potassium    4.7        Milligrams (mg)
26               choline    550        Milligrams (mg)
29               protein     50              Grams (g)

In [65]:
nutrients_table = pd.DataFrame(columns = {'Nutrients', 'Norma', 'measure', 'product'})
count = 0
for i in trange(len(nutr_url)):
    b = nutr_url['nutrition'].values[i]
    for j in range(len(df_nutr)):
        a = df_nutr['Nutrient'].values[j]
        if a in b:
            nutrients_table.loc[len(nutrients_table.index)] = [df_nutr['Nutrient'].values[j],
                                           (nutr_url['value'].values[i]/float(df_nutr['Norma'].values[j]))*100, 
                                           df_nutr['Unit of measure'].values[j], 
                                           nutr_url['food_product'].values[i]]

100%|█████████████████████████████████████████████████████████████████████████████| 8622/8622 [00:16<00:00, 507.60it/s]

In [66]:
nutrients_table

          product    Nutrients                  Norma measure
0         protein    11.133333              Grams (g)  rating
1         protein    33.400000              Grams (g)  rating
2             fat    33.707865              Grams (g)  rating
3         calcium  5153.846154        Milligrams (mg)  rating
4            iron    33.333333        Milligrams (mg)  rating
...           ...          ...                    ...     ...
4018    vitamin a    58.888889  Micrograms RAE2 (mcg)  turkey
4019    vitamin c     0.000000        Milligrams (mg)  turkey
4020  cholesterol    11.333333        Milligrams (mg)  turkey
4021          fat     0.000000              Grams (g)  turkey
4022          fat     0.235955              Grams (g)  turkey

[4023 rows x 4 columns]

In [83]:
nutrients_table = pd.read_csv('C:\\Google Drive\\School21\\Day15\\Nutrition_final.csv')
nutrients_table

      Unnamed: 0      product    Nutrients                  Norma measure
0              0      protein    11.133333              Grams (g)  rating
1              1      protein    33.400000              Grams (g)  rating
2              2          fat    33.707865              Grams (g)  rating
3              3      calcium  5153.846154        Milligrams (mg)  rating
4              4         iron    33.333333        Milligrams (mg)  rating
...          ...          ...          ...                    ...     ...
4018        4018    vitamin a    58.888889  Micrograms RAE2 (mcg)  turkey
4019        4019    vitamin c     0.000000        Milligrams (mg)  turkey
4020        4020  cholesterol    11.333333        Milligrams (mg)  turkey
4021        4021          fat     0.000000              Grams (g)  turkey
4022        4022          fat     0.235955              Grams (g)  turkey

[4023 rows x 5 columns]

In [84]:
nutrients_table = nutrients_table.set_index('measure')

In [85]:
nutrients_table

         Unnamed: 0      product    Nutrients                  Norma
measure
rating            0      protein    11.133333              Grams (g)
rating            1      protein    33.400000              Grams (g)
rating            2          fat    33.707865              Grams (g)
rating            3      calcium  5153.846154        Milligrams (mg)
rating            4         iron    33.333333        Milligrams (mg)
...             ...          ...          ...                    ...
turkey         4018    vitamin a    58.888889  Micrograms RAE2 (mcg)
turkey         4019    vitamin c     0.000000        Milligrams (mg)
turkey         4020  cholesterol    11.333333        Milligrams (mg)
turkey         4021          fat     0.000000              Grams (g)
turkey         4022          fat     0.235955              Grams (g)

[4023 rows x 4 columns]

In [87]:
nutrients_table = nutrients_table.drop(['rating'],axis = 0)
nutrients_table

         Unnamed: 0      product     Nutrients                  Norma
measure
almond           11      protein     14.000000              Grams (g)
almond           12      protein     42.000000              Grams (g)
almond           13          fat     31.179775              Grams (g)
almond           14      calcium  26692.307692        Milligrams (mg)
almond           15         iron     19.388889        Milligrams (mg)
...             ...          ...           ...                    ...
turkey         4018    vitamin a     58.888889  Micrograms RAE2 (mcg)
turkey         4019    vitamin c      0.000000        Milligrams (mg)
turkey         4020  cholesterol     11.333333        Milligrams (mg)
turkey         4021          fat      0.000000              Grams (g)
turkey         4022          fat      0.235955              Grams (g)

[4012 rows x 4 columns]

In [88]:
nutrients_table.to_csv('C:\\Google Drive\\School21\\Day15\\Nutrition_final.csv')